sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pydocstyle ssm/
  - isort --check-only --verbose --recursive ssm/
  - pylint ssm/
  - bandit -r ssm/
  - py.test --cov=ssm ssm/tests
after_success:
  - coveralls
